import { readFile, unlink, writeFile } from "node:fs/promises";
import { basename, join } from "node:path";
import { agentFiles, forEachAgentPath } from "./AgentFiles.ts";
import { fileExists, isSymlink, walkDirectory } from "./FsUtil.ts";
import type { GitContext } from "./Git.ts";
import { overlayProjectDir, overlayWorktreeDir } from "./Mapper.ts";

/** Params for the consolidation entry point */
export interface ConsolidateParams {
  overlayRoot: string;
  targetRoot: string;
  gitContext: GitContext;
  agents: string[];
}

/** A rules file with its parsed metadata and content */
interface RuleFile {
  filename: string;
  content: string;
  description?: string;
  paths?: string;
}

/** First-line marker for generated agent files */
export const generatedMarker = "<!-- Generated by clank";

/**
 * Consolidate agents.md + .claude/rules/ into generated AGENTS.md/GEMINI.md.
 *
 * Only runs when rules files exist in the overlay. Root-level only --
 * subdirectory agents.md files continue as pure symlinks.
 */
export async function consolidateRulesIntoAgentFiles(
  params: ConsolidateParams,
): Promise<string[]> {
  const { overlayRoot, targetRoot, gitContext, agents } = params;

  // Collect rules from all applicable overlay scopes
  const rulesFiles = await collectRulesFiles(overlayRoot, gitContext);
  if (rulesFiles.length === 0) return [];

  // Read root-level agents.md from overlay (if exists)
  const agentsMdContent = await readRootAgentsMd(overlayRoot, gitContext);

  // Build the consolidated content
  const overlayPaths = getOverlayPaths(overlayRoot, gitContext);
  const merged = buildConsolidatedContent(
    agentsMdContent,
    rulesFiles,
    overlayPaths,
  );

  // For each non-claude agent, replace the symlink with a generated file
  const generated: string[] = [];
  await forEachAgentPath(targetRoot, agents, async (agentPath, agentName) => {
    if (agentName.toLowerCase() === "claude") return;
    // Remove existing symlink if present
    if (await isSymlink(agentPath)) {
      await unlink(agentPath);
    }
    await writeFile(agentPath, merged, "utf-8");
    generated.push(basename(agentPath));
  });

  return generated;
}

/** Check if a file is generated by clank (first line starts with marker) */
export async function isGeneratedByClank(filePath: string): Promise<boolean> {
  if (!(await fileExists(filePath))) return false;
  if (await isSymlink(filePath)) return false;
  try {
    const content = await readFile(filePath, "utf-8");
    return content.startsWith(generatedMarker);
  } catch {
    return false;
  }
}

/** Strip YAML frontmatter and extract description/paths */
export function stripFrontmatter(raw: string): {
  content: string;
  description?: string;
  paths?: string;
} {
  const fence = "---";
  const fenceNewline = `\n${fence}`;

  if (!raw.startsWith(fence)) {
    return { content: raw };
  }

  const endIndex = raw.indexOf(fenceNewline, fence.length);
  if (endIndex === -1) {
    return { content: raw };
  }

  const frontmatter = raw.slice(fence.length, endIndex).trim();
  const content = raw.slice(endIndex + fenceNewline.length).replace(/^\n+/, "");

  let description: string | undefined;
  let paths: string | undefined;

  for (const line of frontmatter.split("\n")) {
    const descMatch = line.match(/^description:\s*(.+)/);
    if (descMatch) {
      description = descMatch[1].trim().replace(/^["']|["']$/g, "");
    }
    const pathsMatch = line.match(/^paths:\s*(.+)/);
    if (pathsMatch) {
      // paths can be inline array: ["src/**/*.ts"] or plain string
      paths = pathsMatch[1]
        .trim()
        .replace(/^\[|\]$/g, "")
        .replace(/["']/g, "");
    }
  }

  return { content, description, paths };
}

/** Convert a filename to a human-readable heading */
export function humanizeFilename(filename: string): string {
  return filename.replace(/\.md$/, "").replace(/[-_]/g, " ");
}

/** Remove generated agent files from target (for unlink) */
export async function removeGeneratedAgentFiles(
  targetRoot: string,
): Promise<string[]> {
  const removed: string[] = [];
  for (const name of agentFiles) {
    const path = join(targetRoot, name);
    if (await isGeneratedByClank(path)) {
      await unlink(path);
      removed.push(name);
    }
  }
  return removed;
}

/** Collect all .md files from claude/rules/ across overlay scopes */
async function collectRulesFiles(
  overlayRoot: string,
  gitContext: GitContext,
): Promise<RuleFile[]> {
  const dirs = [
    join(overlayRoot, "global/claude/rules"),
    join(overlayProjectDir(overlayRoot, gitContext.projectName), "claude/rules"),
    join(overlayWorktreeDir(overlayRoot, gitContext), "claude/rules"),
  ];

  const allFiles: RuleFile[] = [];
  for (const dir of dirs) {
    if (!(await fileExists(dir))) continue;
    for await (const { path, isDirectory } of walkDirectory(dir)) {
      if (isDirectory) continue;
      if (!path.endsWith(".md")) continue;
      const raw = await readFile(path, "utf-8");
      const parsed = stripFrontmatter(raw);
      allFiles.push({
        filename: basename(path),
        ...parsed,
      });
    }
  }

  // Sort alphabetically by filename for deterministic output
  allFiles.sort((a, b) => a.filename.localeCompare(b.filename));
  return allFiles;
}

/** Read root-level agents.md from the overlay (project scope, then global) */
async function readRootAgentsMd(
  overlayRoot: string,
  gitContext: GitContext,
): Promise<string | null> {
  const projectPath = join(
    overlayProjectDir(overlayRoot, gitContext.projectName),
    "agents.md",
  );
  if (await fileExists(projectPath)) {
    return readFile(projectPath, "utf-8");
  }

  // Fall back to global agents.md
  const globalPath = join(overlayRoot, "global/agents.md");
  if (await fileExists(globalPath)) {
    return readFile(globalPath, "utf-8");
  }

  return null;
}

/** Get overlay paths for the header comments */
function getOverlayPaths(
  overlayRoot: string,
  gitContext: GitContext,
): { agentsMdPath: string; rulesDir: string } {
  const projectDir = overlayProjectDir(overlayRoot, gitContext.projectName);
  return {
    agentsMdPath: join(projectDir, "agents.md"),
    rulesDir: join(projectDir, "claude/rules"),
  };
}

/** Build the consolidated markdown content */
function buildConsolidatedContent(
  agentsMdContent: string | null,
  rules: RuleFile[],
  overlayPaths: { agentsMdPath: string; rulesDir: string },
): string {
  const lines: string[] = [];

  // Header comments
  lines.push(`${generatedMarker} - do not edit -->`);
  if (agentsMdContent) {
    lines.push(`<!-- Source: ${overlayPaths.agentsMdPath} -->`);
  }
  lines.push(`<!-- Rules: ${overlayPaths.rulesDir} -->`);
  lines.push("");

  // Base agents.md content
  if (agentsMdContent) {
    lines.push(agentsMdContent.trimEnd());
  }

  // Append each rule as a section
  for (const rule of rules) {
    lines.push("");
    lines.push("---");
    lines.push("");

    const heading = rule.description || humanizeFilename(rule.filename);
    lines.push(`## ${heading}`);

    if (rule.paths) {
      lines.push(`Applies to: ${rule.paths}`);
    }

    lines.push("");
    lines.push(rule.content.trimEnd());
  }

  lines.push("");
  return lines.join("\n");
}
